"""Add verification codes

Revision ID: bfcad48a09a7
Revises: 1d2e9cdd8298
Create Date: 2026-02-21 23:05:28.560150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcad48a09a7'
down_revision = '1d2e9cdd8298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_phone'), ['phone'], unique=False)

    op.create_table('document_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_status'))

    op.drop_table('verifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_column('is_phone_verified')
        batch_op.drop_column('phone')

    op.create_table('verifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('verification_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('document_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('review_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_status'), ['status'], unique=False)

    op.drop_table('document_verifications')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_phone'))

    op.drop_table('verification_codes')
    # ### end Alembic commands ###
